name: Build Obfuscate BPB Panel

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 安装依赖
        run: |
          npm install -g javascript-obfuscator
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: 下载并解压最新的 BPB Worker
        run: |
          wget https://github.com/bia-pain-bache/BPB-Worker-Panel/releases/latest/download/unobfuscated-worker.zip
          if [ ! -f "unobfuscated-worker.zip" ]; then
            echo "错误：未下载到 ZIP 文件"
            exit 1
          fi
          unzip -o unobfuscated-worker.zip
          if [ ! -f "_worker.js" ]; then
            echo "错误：解压后未找到 _worker.js"
            exit 1
          fi
          mv _worker.js origin.js

      - name: 混淆 BPB Worker JS
        run: |
          javascript-obfuscator origin.js --output _worker.js \
            --compact true \
            --identifier-names-generator hexadecimal \
            --rename-globals true \
            --string-array true \
            --string-array-encoding 'base64' \
            --string-array-threshold 0.75 \
            --transform-object-keys true \
            --self-defending false \
            --simplify true
          if [ ! -f "_worker.js" ]; then
            echo "错误：未生成混淆后的 _worker.js"
            exit 1
          fi

      - name: 调试文件状态
        run: |
          ls -la
          cat _worker.js | head -n 10

      - name: 提交并推送更改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ':arrow_up: 更新最新的 BPB Panel'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          file_pattern: '_worker.js'
